### ISSUE TITLE
ECPairFactory is not a function

### ISSUE THREAD

**Issue by Alf71** [antonilol/btc_stuff#3]
TypeError: require(...).ECPairFactory is not a function

**Comment by antonilol** [comment]
Did you `npm install`?

**Comment by Alf71** [comment]
Ja, both:

npm install bitcoinjs-lib
npm install ecpair

**Comment by antonilol** [comment]
Which script did you try to run?
Which OS do you have and which node and npm version do you run?

What does `require('ecpair')` print in nodejs repl?

**Comment by Alf71** [comment]
I'm getting

{
  networks: {
    bitcoin: {
      messagePrefix: '\x18Bitcoin Signed Message:\n',
      bech32: 'bc',
      bip32: [Object],
      pubKeyHash: 0,
      scriptHash: 5,
      wif: 128
    },
    testnet: {
      messagePrefix: '\x18Bitcoin Signed Message:\n',
      bech32: 'tb',
      bip32: [Object],
      pubKeyHash: 111,
      scriptHash: 196,
      wif: 239
    }
  },
  ECPair: [class ECPair]
}

**Comment by Alf71** [comment]
cat node_modules/ecpair/package.json | grep version
cat: node_modules/ecpair/package.json: No such file or directory

**Comment by antonilol** [comment]
looks like a really old version of bitcoinjs lib and ecpair
i think this patch will fix it but consider updating your node/npm

```patch
diff --git a/priv_key_recovery.js b/priv_key_recovery.js
index 35fd65d..40b68db 100644
--- a/priv_key_recovery.js
+++ b/priv_key_recovery.js
@@ -1,5 +1,5 @@
 const bitcoin = require('bitcoinjs-lib');
-const ECPair = require('ecpair').ECPairFactory(require('tiny-secp256k1'));
+const { ECPair } = require('ecpair');
 
 const base58chars = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'.split('');
```

**Comment by Alf71** [comment]
Thanks
